# Generated by Django 5.0.3 on 2024-04-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
